version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - "${PWD}/public/:/etc/nginx/static:ro"
      - "${PWD}/deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/https/sert.pem:/etc/https/sert.pem:ro"
      - "/etc/https/key.pem:/etc/https/key.pem:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend-service-network

networks:
  frontend-service-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1